### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by Venryx** [seanchas116/node-tflite#10]
I get the following error when attempting to import and use the package, in Electron:
```
Error: Could not locate the bindings file. Tried:
 → C:\Root\Apps\@V\LucidFrontier\Desktop\build\node_tflite.node
 → C:\Root\Apps\@V\LucidFrontier\Desktop\build\Debug\node_tflite.node
 → C:\Root\Apps\@V\LucidFrontier\Desktop\build\Release\node_tflite.node
 → C:\Root\Apps\@V\LucidFrontier\Desktop\out\Debug\node_tflite.node
 → C:\Root\Apps\@V\LucidFrontier\Desktop\Debug\node_tflite.node
 → C:\Root\Apps\@V\LucidFrontier\Desktop\out\Release\node_tflite.node
 → C:\Root\Apps\@V\LucidFrontier\Desktop\Release\node_tflite.node
 → C:\Root\Apps\@V\LucidFrontier\Desktop\build\default\node_tflite.node
 → C:\Root\Apps\@V\LucidFrontier\Desktop\compiled\14.15.1\win32\x64\node_tflite.node
 → C:\Root\Apps\@V\LucidFrontier\Desktop\addon-build\release\install-root\node_tflite.node
 → C:\Root\Apps\@V\LucidFrontier\Desktop\addon-build\debug\install-root\node_tflite.node
 → C:\Root\Apps\@V\LucidFrontier\Desktop\addon-build\default\install-root\node_tflite.node
 → C:\Root\Apps\@V\LucidFrontier\Desktop\lib\binding\node-v87-win32-x64\node_tflite.node
    at bindings (C:\Root\Apps\@V\LucidFrontier\Desktop\Dist\index.js:115860:9)
    at Object.<anonymous> (C:\Root\Apps\@V\LucidFrontier\Desktop\Dist\index.js:115596:53)
    at __webpack_require__ (C:\Root\Apps\@V\LucidFrontier\Desktop\Dist\index.js:30:30)
    at Module.<anonymous> (C:\Root\Apps\@V\LucidFrontier\Desktop\Dist\index.js:115361:69)
    at __webpack_require__ (C:\Root\Apps\@V\LucidFrontier\Desktop\Dist\index.js:30:30)
    at Module.<anonymous> (C:\Root\Apps\@V\LucidFrontier\Desktop\Dist\index.js:90034:94)
    at __webpack_require__ (C:\Root\Apps\@V\LucidFrontier\Desktop\Dist\index.js:30:30)
    at Object.<anonymous> (C:\Root\Apps\@V\LucidFrontier\Desktop\Dist\index.js:129:5)
    at __webpack_require__ (C:\Root\Apps\@V\LucidFrontier\Desktop\Dist\index.js:30:30)
    at Object.<anonymous> (C:\Root\Apps\@V\LucidFrontier\Desktop\Dist\index.js:105:18)
(anonymous) @ electron/js2c/renderer_init.js:93
```

What's odd to me is that it appears the library is looking for its Node bindings within my project's repo root, rather than looking inside the `node_modules` folder.

Will update this issue as I find out more.

**Comment by Venryx** [comment]
These are the contents of the `node_modules/node-tflite` folder:
![](https://i.imgur.com/ld7MOHt.png)

I do not see a `node_tflite.node` file anywhere within it.

**Comment by Venryx** [comment]
I see the problem... I was using webpack to bundle the Javascript code for the project, and forgot to add `node-tflite` as an "external".

I'm considering using this package to help with this problem in the future: https://www.npmjs.com/package/webpack-node-externals
